// Code generated by MockGen. DO NOT EDIT.
// Source: grpc-app/service/users/user.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	users "go/service1/grpc-app/protos/users"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsersService is a mock of UsersService interface.
type MockUsersService struct {
	ctrl     *gomock.Controller
	recorder *MockUsersServiceMockRecorder
}

// MockUsersServiceMockRecorder is the mock recorder for MockUsersService.
type MockUsersServiceMockRecorder struct {
	mock *MockUsersService
}

// NewMockUsersService creates a new mock instance.
func NewMockUsersService(ctrl *gomock.Controller) *MockUsersService {
	mock := &MockUsersService{ctrl: ctrl}
	mock.recorder = &MockUsersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersService) EXPECT() *MockUsersServiceMockRecorder {
	return m.recorder
}

// SelectSessionUserById mocks base method.
func (m *MockUsersService) SelectSessionUserById(arg0 context.Context, arg1 *users.RequestSelectSessionUserById) (*users.ResponseSelectSessionUserById, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectSessionUserById", arg0, arg1)
	ret0, _ := ret[0].(*users.ResponseSelectSessionUserById)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectSessionUserById indicates an expected call of SelectSessionUserById.
func (mr *MockUsersServiceMockRecorder) SelectSessionUserById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectSessionUserById", reflect.TypeOf((*MockUsersService)(nil).SelectSessionUserById), arg0, arg1)
}

// SelectUser mocks base method.
func (m *MockUsersService) SelectUser(arg0 context.Context, arg1 *users.RequestSelectUser) (*users.ResponseSelectUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUser", arg0, arg1)
	ret0, _ := ret[0].(*users.ResponseSelectUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUser indicates an expected call of SelectUser.
func (mr *MockUsersServiceMockRecorder) SelectUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUser", reflect.TypeOf((*MockUsersService)(nil).SelectUser), arg0, arg1)
}
