// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package users

import (
	"go.uber.org/zap"
	"go/service1/grpc-app/protos/users"
	users4 "go/service1/grpc-app/service/users"
	users2 "go/service1/shared/repository/users"
	users3 "go/service1/shared/usecase/users"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUsersService(db *gorm.DB, logger *zap.Logger) (users.UserRPCServer, error) {
	userRepository := users2.NewUsersRepositoryImpl(db, logger)
	usersUseCase := users3.NewUsersUseCaseImpl(userRepository, logger)
	userRPCServer := users4.NewUserServiceImpl(usersUseCase, logger)
	return userRPCServer, nil
}
