// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protos/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthRPCClient is the client API for AuthRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthRPCClient interface {
	RegisterUser(ctx context.Context, in *RequestRegister, opts ...grpc.CallOption) (*ResponseRegister, error)
	LoginUser(ctx context.Context, in *RequestLogin, opts ...grpc.CallOption) (*ResponseLogin, error)
}

type authRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthRPCClient(cc grpc.ClientConnInterface) AuthRPCClient {
	return &authRPCClient{cc}
}

func (c *authRPCClient) RegisterUser(ctx context.Context, in *RequestRegister, opts ...grpc.CallOption) (*ResponseRegister, error) {
	out := new(ResponseRegister)
	err := c.cc.Invoke(ctx, "/protos.AuthRPC/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authRPCClient) LoginUser(ctx context.Context, in *RequestLogin, opts ...grpc.CallOption) (*ResponseLogin, error) {
	out := new(ResponseLogin)
	err := c.cc.Invoke(ctx, "/protos.AuthRPC/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthRPCServer is the server API for AuthRPC service.
// All implementations must embed UnimplementedAuthRPCServer
// for forward compatibility
type AuthRPCServer interface {
	RegisterUser(context.Context, *RequestRegister) (*ResponseRegister, error)
	LoginUser(context.Context, *RequestLogin) (*ResponseLogin, error)
	mustEmbedUnimplementedAuthRPCServer()
}

// UnimplementedAuthRPCServer must be embedded to have forward compatible implementations.
type UnimplementedAuthRPCServer struct {
}

func (UnimplementedAuthRPCServer) RegisterUser(context.Context, *RequestRegister) (*ResponseRegister, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedAuthRPCServer) LoginUser(context.Context, *RequestLogin) (*ResponseLogin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedAuthRPCServer) mustEmbedUnimplementedAuthRPCServer() {}

// UnsafeAuthRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthRPCServer will
// result in compilation errors.
type UnsafeAuthRPCServer interface {
	mustEmbedUnimplementedAuthRPCServer()
}

func RegisterAuthRPCServer(s grpc.ServiceRegistrar, srv AuthRPCServer) {
	s.RegisterService(&AuthRPC_ServiceDesc, srv)
}

func _AuthRPC_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthRPCServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthRPC/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthRPCServer).RegisterUser(ctx, req.(*RequestRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthRPC_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthRPCServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthRPC/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthRPCServer).LoginUser(ctx, req.(*RequestLogin))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthRPC_ServiceDesc is the grpc.ServiceDesc for AuthRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AuthRPC",
	HandlerType: (*AuthRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _AuthRPC_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _AuthRPC_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/auth.proto",
}
