// Code generated by MockGen. DO NOT EDIT.
// Source: shared/usecase/users/user.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	users "go/service1/grpc-app/protos/users"
	entities "go/service1/shared/models/entities"
	table "go/service1/shared/models/entities/table"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsersUseCase is a mock of UsersUseCase interface.
type MockUsersUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUsersUseCaseMockRecorder
}

// MockUsersUseCaseMockRecorder is the mock recorder for MockUsersUseCase.
type MockUsersUseCaseMockRecorder struct {
	mock *MockUsersUseCase
}

// NewMockUsersUseCase creates a new mock instance.
func NewMockUsersUseCase(ctrl *gomock.Controller) *MockUsersUseCase {
	mock := &MockUsersUseCase{ctrl: ctrl}
	mock.recorder = &MockUsersUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersUseCase) EXPECT() *MockUsersUseCaseMockRecorder {
	return m.recorder
}

// SelectSessionUserById mocks base method.
func (m *MockUsersUseCase) SelectSessionUserById(arg0 context.Context, arg1 *users.RequestSelectSessionUserById) (*entities.ResponSelectSessionUserById, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectSessionUserById", arg0, arg1)
	ret0, _ := ret[0].(*entities.ResponSelectSessionUserById)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectSessionUserById indicates an expected call of SelectSessionUserById.
func (mr *MockUsersUseCaseMockRecorder) SelectSessionUserById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectSessionUserById", reflect.TypeOf((*MockUsersUseCase)(nil).SelectSessionUserById), arg0, arg1)
}

// SelectUser mocks base method.
func (m *MockUsersUseCase) SelectUser(arg0 context.Context, arg1 *users.RequestSelectUser) (*table.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUser", arg0, arg1)
	ret0, _ := ret[0].(*table.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUser indicates an expected call of SelectUser.
func (mr *MockUsersUseCaseMockRecorder) SelectUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUser", reflect.TypeOf((*MockUsersUseCase)(nil).SelectUser), arg0, arg1)
}
