// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: image.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageRPCClient is the client API for ImageRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageRPCClient interface {
	InsertProductId(ctx context.Context, in *DataProduct, opts ...grpc.CallOption) (*ResponseInsertProductID, error)
}

type imageRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewImageRPCClient(cc grpc.ClientConnInterface) ImageRPCClient {
	return &imageRPCClient{cc}
}

func (c *imageRPCClient) InsertProductId(ctx context.Context, in *DataProduct, opts ...grpc.CallOption) (*ResponseInsertProductID, error) {
	out := new(ResponseInsertProductID)
	err := c.cc.Invoke(ctx, "/protos.ImageRPC/InsertProductId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageRPCServer is the server API for ImageRPC service.
// All implementations must embed UnimplementedImageRPCServer
// for forward compatibility
type ImageRPCServer interface {
	InsertProductId(context.Context, *DataProduct) (*ResponseInsertProductID, error)
	mustEmbedUnimplementedImageRPCServer()
}

// UnimplementedImageRPCServer must be embedded to have forward compatible implementations.
type UnimplementedImageRPCServer struct {
}

func (UnimplementedImageRPCServer) InsertProductId(context.Context, *DataProduct) (*ResponseInsertProductID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertProductId not implemented")
}
func (UnimplementedImageRPCServer) mustEmbedUnimplementedImageRPCServer() {}

// UnsafeImageRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageRPCServer will
// result in compilation errors.
type UnsafeImageRPCServer interface {
	mustEmbedUnimplementedImageRPCServer()
}

func RegisterImageRPCServer(s grpc.ServiceRegistrar, srv ImageRPCServer) {
	s.RegisterService(&ImageRPC_ServiceDesc, srv)
}

func _ImageRPC_InsertProductId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRPCServer).InsertProductId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ImageRPC/InsertProductId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRPCServer).InsertProductId(ctx, req.(*DataProduct))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageRPC_ServiceDesc is the grpc.ServiceDesc for ImageRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ImageRPC",
	HandlerType: (*ImageRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertProductId",
			Handler:    _ImageRPC_InsertProductId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "image.proto",
}
