// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"go.uber.org/zap"
	"go/service1/grpc-app/protos/auth"
	auth4 "go/service1/grpc-app/service/auth"
	auth2 "go/service1/shared/repository/auth"
	auth3 "go/service1/shared/usecase/auth"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthService(db *gorm.DB, logger *zap.Logger) (auth.AuthRPCServer, error) {
	authRepository := auth2.NewAuthRepositoryImpl(db, logger)
	authUseCase := auth3.NewAuthUseCaseImpl(authRepository, logger)
	authRPCServer := auth4.NewAuthService(authUseCase, logger)
	return authRPCServer, nil
}
